# Generated by Django 4.1.13 on 2024-04-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_api', '0002_remove_user_name_column_date_column_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
